@URL=http://localhost:8081/api/v1


### - criar jogador -
POST {{URL}}/jogadores HTTP/1.1
Content-Type: application/json

{
  "telefoneCelular": "55678993",
  "email": "robsom@smartranking.com",
  "nome": "robsom gomes"
}